// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.29.1
// source: account-grpc.proto

/* eslint-disable */
import {
  type CallOptions,
  ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import _m0 from "protobufjs/minimal";
import { Account, AccountID, UserStatus, userStatusFromJSON, userStatusToJSON } from "./account";
import { Empty } from "./google/protobuf/empty";
import { Audit } from "./sologenic/com-fs-utils-lib/models/audit/audit";
import { Network, networkFromJSON, networkToJSON } from "./sologenic/com-fs-utils-lib/models/metadata/metadata";

export const protobufPackage = "account";

export interface KYCApplicationID {
  /** UUID for the external user identifier in the KYC provider (called "externalUserID" in sumsub) */
  KYCApplicationID: string;
}

export interface SetStatusMessage {
  AccountID: string;
  Status: UserStatus;
  Network?: Network | undefined;
  Audit: Audit | undefined;
}

function createBaseKYCApplicationID(): KYCApplicationID {
  return { KYCApplicationID: "" };
}

export const KYCApplicationID = {
  encode(message: KYCApplicationID, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.KYCApplicationID !== "") {
      writer.uint32(10).string(message.KYCApplicationID);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): KYCApplicationID {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseKYCApplicationID();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.KYCApplicationID = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): KYCApplicationID {
    return { KYCApplicationID: isSet(object.KYCApplicationID) ? globalThis.String(object.KYCApplicationID) : "" };
  },

  toJSON(message: KYCApplicationID): unknown {
    const obj: any = {};
    if (message.KYCApplicationID !== "") {
      obj.KYCApplicationID = message.KYCApplicationID;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<KYCApplicationID>, I>>(base?: I): KYCApplicationID {
    return KYCApplicationID.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<KYCApplicationID>, I>>(object: I): KYCApplicationID {
    const message = createBaseKYCApplicationID();
    message.KYCApplicationID = object.KYCApplicationID ?? "";
    return message;
  },
};

function createBaseSetStatusMessage(): SetStatusMessage {
  return { AccountID: "", Status: 0, Network: undefined, Audit: undefined };
}

export const SetStatusMessage = {
  encode(message: SetStatusMessage, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.AccountID !== "") {
      writer.uint32(10).string(message.AccountID);
    }
    if (message.Status !== 0) {
      writer.uint32(16).int32(message.Status);
    }
    if (message.Network !== undefined) {
      writer.uint32(24).int32(message.Network);
    }
    if (message.Audit !== undefined) {
      Audit.encode(message.Audit, writer.uint32(34).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SetStatusMessage {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetStatusMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.AccountID = reader.string();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.Status = reader.int32() as any;
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.Network = reader.int32() as any;
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.Audit = Audit.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SetStatusMessage {
    return {
      AccountID: isSet(object.AccountID) ? globalThis.String(object.AccountID) : "",
      Status: isSet(object.Status) ? userStatusFromJSON(object.Status) : 0,
      Network: isSet(object.Network) ? networkFromJSON(object.Network) : undefined,
      Audit: isSet(object.Audit) ? Audit.fromJSON(object.Audit) : undefined,
    };
  },

  toJSON(message: SetStatusMessage): unknown {
    const obj: any = {};
    if (message.AccountID !== "") {
      obj.AccountID = message.AccountID;
    }
    if (message.Status !== 0) {
      obj.Status = userStatusToJSON(message.Status);
    }
    if (message.Network !== undefined) {
      obj.Network = networkToJSON(message.Network);
    }
    if (message.Audit !== undefined) {
      obj.Audit = Audit.toJSON(message.Audit);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SetStatusMessage>, I>>(base?: I): SetStatusMessage {
    return SetStatusMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SetStatusMessage>, I>>(object: I): SetStatusMessage {
    const message = createBaseSetStatusMessage();
    message.AccountID = object.AccountID ?? "";
    message.Status = object.Status ?? 0;
    message.Network = object.Network ?? undefined;
    message.Audit = (object.Audit !== undefined && object.Audit !== null) ? Audit.fromPartial(object.Audit) : undefined;
    return message;
  },
};

export type AccountServiceService = typeof AccountServiceService;
export const AccountServiceService = {
  get: {
    path: "/account.AccountService/Get",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: AccountID) => Buffer.from(AccountID.encode(value).finish()),
    requestDeserialize: (value: Buffer) => AccountID.decode(value),
    responseSerialize: (value: Account) => Buffer.from(Account.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Account.decode(value),
  },
  geyByKycApplicationId: {
    path: "/account.AccountService/GeyByKYCApplicationID",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: KYCApplicationID) => Buffer.from(KYCApplicationID.encode(value).finish()),
    requestDeserialize: (value: Buffer) => KYCApplicationID.decode(value),
    responseSerialize: (value: Account) => Buffer.from(Account.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Account.decode(value),
  },
  upsert: {
    path: "/account.AccountService/Upsert",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: Account) => Buffer.from(Account.encode(value).finish()),
    requestDeserialize: (value: Buffer) => Account.decode(value),
    responseSerialize: (value: AccountID) => Buffer.from(AccountID.encode(value).finish()),
    responseDeserialize: (value: Buffer) => AccountID.decode(value),
  },
  setStatus: {
    path: "/account.AccountService/SetStatus",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: SetStatusMessage) => Buffer.from(SetStatusMessage.encode(value).finish()),
    requestDeserialize: (value: Buffer) => SetStatusMessage.decode(value),
    responseSerialize: (value: Empty) => Buffer.from(Empty.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Empty.decode(value),
  },
} as const;

export interface AccountServiceServer extends UntypedServiceImplementation {
  get: handleUnaryCall<AccountID, Account>;
  geyByKycApplicationId: handleUnaryCall<KYCApplicationID, Account>;
  upsert: handleUnaryCall<Account, AccountID>;
  setStatus: handleUnaryCall<SetStatusMessage, Empty>;
}

export interface AccountServiceClient extends Client {
  get(request: AccountID, callback: (error: ServiceError | null, response: Account) => void): ClientUnaryCall;
  get(
    request: AccountID,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Account) => void,
  ): ClientUnaryCall;
  get(
    request: AccountID,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Account) => void,
  ): ClientUnaryCall;
  geyByKycApplicationId(
    request: KYCApplicationID,
    callback: (error: ServiceError | null, response: Account) => void,
  ): ClientUnaryCall;
  geyByKycApplicationId(
    request: KYCApplicationID,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Account) => void,
  ): ClientUnaryCall;
  geyByKycApplicationId(
    request: KYCApplicationID,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Account) => void,
  ): ClientUnaryCall;
  upsert(request: Account, callback: (error: ServiceError | null, response: AccountID) => void): ClientUnaryCall;
  upsert(
    request: Account,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: AccountID) => void,
  ): ClientUnaryCall;
  upsert(
    request: Account,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: AccountID) => void,
  ): ClientUnaryCall;
  setStatus(
    request: SetStatusMessage,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  setStatus(
    request: SetStatusMessage,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  setStatus(
    request: SetStatusMessage,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
}

export const AccountServiceClient = makeGenericClientConstructor(
  AccountServiceService,
  "account.AccountService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): AccountServiceClient;
  service: typeof AccountServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
