// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: user-fundings.proto

package user

import (
	order_properties "github.com/sologenic/com-fs-utils-lib/models/order-properties"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignerType int32

const (
	SignerType_NOT_USER_SIGNETTYPE  SignerType = 0
	SignerType_MOBILE_APP           SignerType = 1
	SignerType_BROWSER_LEAP         SignerType = 2
	SignerType_BROWSER_COSMOSTATION SignerType = 3
	SignerType_BROWSER_KEPLR        SignerType = 4
)

// Enum value maps for SignerType.
var (
	SignerType_name = map[int32]string{
		0: "NOT_USER_SIGNETTYPE",
		1: "MOBILE_APP",
		2: "BROWSER_LEAP",
		3: "BROWSER_COSMOSTATION",
		4: "BROWSER_KEPLR",
	}
	SignerType_value = map[string]int32{
		"NOT_USER_SIGNETTYPE":  0,
		"MOBILE_APP":           1,
		"BROWSER_LEAP":         2,
		"BROWSER_COSMOSTATION": 3,
		"BROWSER_KEPLR":        4,
	}
)

func (x SignerType) Enum() *SignerType {
	p := new(SignerType)
	*p = x
	return p
}

func (x SignerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SignerType) Descriptor() protoreflect.EnumDescriptor {
	return file_user_fundings_proto_enumTypes[0].Descriptor()
}

func (SignerType) Type() protoreflect.EnumType {
	return &file_user_fundings_proto_enumTypes[0]
}

func (x SignerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SignerType.Descriptor instead.
func (SignerType) EnumDescriptor() ([]byte, []int) {
	return file_user_fundings_proto_rawDescGZIP(), []int{0}
}

type WalletType int32

const (
	WalletType_NOT_USED_WALLETTYPE WalletType = 0
	WalletType_TFSA                WalletType = 1
	WalletType_RRSP                WalletType = 2
	WalletType_STANDARD            WalletType = 3
)

// Enum value maps for WalletType.
var (
	WalletType_name = map[int32]string{
		0: "NOT_USED_WALLETTYPE",
		1: "TFSA",
		2: "RRSP",
		3: "STANDARD",
	}
	WalletType_value = map[string]int32{
		"NOT_USED_WALLETTYPE": 0,
		"TFSA":                1,
		"RRSP":                2,
		"STANDARD":            3,
	}
)

func (x WalletType) Enum() *WalletType {
	p := new(WalletType)
	*p = x
	return p
}

func (x WalletType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WalletType) Descriptor() protoreflect.EnumDescriptor {
	return file_user_fundings_proto_enumTypes[1].Descriptor()
}

func (WalletType) Type() protoreflect.EnumType {
	return &file_user_fundings_proto_enumTypes[1]
}

func (x WalletType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WalletType.Descriptor instead.
func (WalletType) EnumDescriptor() ([]byte, []int) {
	return file_user_fundings_proto_rawDescGZIP(), []int{1}
}

type Wallet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	Alias         string                 `protobuf:"bytes,2,opt,name=Alias,proto3" json:"Alias,omitempty"`
	Type          WalletType             `protobuf:"varint,3,opt,name=Type,proto3,enum=user.WalletType" json:"Type,omitempty"`
	SignerType    SignerType             `protobuf:"varint,4,opt,name=SignerType,proto3,enum=user.SignerType" json:"SignerType,omitempty"`
	Organizations []string               `protobuf:"bytes,5,rep,name=Organizations,proto3" json:"Organizations,omitempty"` // List of organizations linked to this wallet address
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wallet) Reset() {
	*x = Wallet{}
	mi := &file_user_fundings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wallet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wallet) ProtoMessage() {}

func (x *Wallet) ProtoReflect() protoreflect.Message {
	mi := &file_user_fundings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wallet.ProtoReflect.Descriptor instead.
func (*Wallet) Descriptor() ([]byte, []int) {
	return file_user_fundings_proto_rawDescGZIP(), []int{0}
}

func (x *Wallet) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Wallet) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *Wallet) GetType() WalletType {
	if x != nil {
		return x.Type
	}
	return WalletType_NOT_USED_WALLETTYPE
}

func (x *Wallet) GetSignerType() SignerType {
	if x != nil {
		return x.SignerType
	}
	return SignerType_NOT_USER_SIGNETTYPE
}

func (x *Wallet) GetOrganizations() []string {
	if x != nil {
		return x.Organizations
	}
	return nil
}

type BankAccount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountName   string                 `protobuf:"bytes,1,opt,name=AccountName,proto3" json:"AccountName,omitempty"`
	BankName      string                 `protobuf:"bytes,2,opt,name=BankName,proto3" json:"BankName,omitempty"`           // user's identifier in the bank account
	BankAddress   string                 `protobuf:"bytes,3,opt,name=BankAddress,proto3" json:"BankAddress,omitempty"`     // bank address
	AccountNumber string                 `protobuf:"bytes,4,opt,name=AccountNumber,proto3" json:"AccountNumber,omitempty"` // bank account number
	ABA           string                 `protobuf:"bytes,5,opt,name=ABA,proto3" json:"ABA,omitempty"`                     // bank routing number
	SWIFT         string                 `protobuf:"bytes,6,opt,name=SWIFT,proto3" json:"SWIFT,omitempty"`
	IBAN          string                 `protobuf:"bytes,7,opt,name=IBAN,proto3" json:"IBAN,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BankAccount) Reset() {
	*x = BankAccount{}
	mi := &file_user_fundings_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BankAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankAccount) ProtoMessage() {}

func (x *BankAccount) ProtoReflect() protoreflect.Message {
	mi := &file_user_fundings_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BankAccount.ProtoReflect.Descriptor instead.
func (*BankAccount) Descriptor() ([]byte, []int) {
	return file_user_fundings_proto_rawDescGZIP(), []int{1}
}

func (x *BankAccount) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *BankAccount) GetBankName() string {
	if x != nil {
		return x.BankName
	}
	return ""
}

func (x *BankAccount) GetBankAddress() string {
	if x != nil {
		return x.BankAddress
	}
	return ""
}

func (x *BankAccount) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *BankAccount) GetABA() string {
	if x != nil {
		return x.ABA
	}
	return ""
}

func (x *BankAccount) GetSWIFT() string {
	if x != nil {
		return x.SWIFT
	}
	return ""
}

func (x *BankAccount) GetIBAN() string {
	if x != nil {
		return x.IBAN
	}
	return ""
}

type BrokerAccount struct {
	state          protoimpl.MessageState          `protogen:"open.v1"`
	AccountID      string                          `protobuf:"bytes,1,opt,name=AccountID,proto3" json:"AccountID,omitempty"`                                // user's identifier in the broker account
	Broker         order_properties.ClearingBroker `protobuf:"varint,2,opt,name=Broker,proto3,enum=orderproperties.ClearingBroker" json:"Broker,omitempty"` // "RQD", etc.
	OrganizationID string                          `protobuf:"bytes,3,opt,name=OrganizationID,proto3" json:"OrganizationID,omitempty"`                      // broker identifier
	Profiles       []string                        `protobuf:"bytes,4,rep,name=Profiles,proto3" json:"Profiles,omitempty"`                                  // bank account profiles for the broker account
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BrokerAccount) Reset() {
	*x = BrokerAccount{}
	mi := &file_user_fundings_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrokerAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrokerAccount) ProtoMessage() {}

func (x *BrokerAccount) ProtoReflect() protoreflect.Message {
	mi := &file_user_fundings_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrokerAccount.ProtoReflect.Descriptor instead.
func (*BrokerAccount) Descriptor() ([]byte, []int) {
	return file_user_fundings_proto_rawDescGZIP(), []int{2}
}

func (x *BrokerAccount) GetAccountID() string {
	if x != nil {
		return x.AccountID
	}
	return ""
}

func (x *BrokerAccount) GetBroker() order_properties.ClearingBroker {
	if x != nil {
		return x.Broker
	}
	return order_properties.ClearingBroker(0)
}

func (x *BrokerAccount) GetOrganizationID() string {
	if x != nil {
		return x.OrganizationID
	}
	return ""
}

func (x *BrokerAccount) GetProfiles() []string {
	if x != nil {
		return x.Profiles
	}
	return nil
}

var File_user_fundings_proto protoreflect.FileDescriptor

const file_user_fundings_proto_rawDesc = "" +
	"\n" +
	"\x13user-fundings.proto\x12\x04user\x1aIsologenic/com-fs-utils-lib/models/order-properties/order-properties.proto\"\xb6\x01\n" +
	"\x06Wallet\x12\x18\n" +
	"\aAddress\x18\x01 \x01(\tR\aAddress\x12\x14\n" +
	"\x05Alias\x18\x02 \x01(\tR\x05Alias\x12$\n" +
	"\x04Type\x18\x03 \x01(\x0e2\x10.user.WalletTypeR\x04Type\x120\n" +
	"\n" +
	"SignerType\x18\x04 \x01(\x0e2\x10.user.SignerTypeR\n" +
	"SignerType\x12$\n" +
	"\rOrganizations\x18\x05 \x03(\tR\rOrganizations\"\xcf\x01\n" +
	"\vBankAccount\x12 \n" +
	"\vAccountName\x18\x01 \x01(\tR\vAccountName\x12\x1a\n" +
	"\bBankName\x18\x02 \x01(\tR\bBankName\x12 \n" +
	"\vBankAddress\x18\x03 \x01(\tR\vBankAddress\x12$\n" +
	"\rAccountNumber\x18\x04 \x01(\tR\rAccountNumber\x12\x10\n" +
	"\x03ABA\x18\x05 \x01(\tR\x03ABA\x12\x14\n" +
	"\x05SWIFT\x18\x06 \x01(\tR\x05SWIFT\x12\x12\n" +
	"\x04IBAN\x18\a \x01(\tR\x04IBAN\"\xaa\x01\n" +
	"\rBrokerAccount\x12\x1c\n" +
	"\tAccountID\x18\x01 \x01(\tR\tAccountID\x127\n" +
	"\x06Broker\x18\x02 \x01(\x0e2\x1f.orderproperties.ClearingBrokerR\x06Broker\x12&\n" +
	"\x0eOrganizationID\x18\x03 \x01(\tR\x0eOrganizationID\x12\x1a\n" +
	"\bProfiles\x18\x04 \x03(\tR\bProfiles*t\n" +
	"\n" +
	"SignerType\x12\x17\n" +
	"\x13NOT_USER_SIGNETTYPE\x10\x00\x12\x0e\n" +
	"\n" +
	"MOBILE_APP\x10\x01\x12\x10\n" +
	"\fBROWSER_LEAP\x10\x02\x12\x18\n" +
	"\x14BROWSER_COSMOSTATION\x10\x03\x12\x11\n" +
	"\rBROWSER_KEPLR\x10\x04*G\n" +
	"\n" +
	"WalletType\x12\x17\n" +
	"\x13NOT_USED_WALLETTYPE\x10\x00\x12\b\n" +
	"\x04TFSA\x10\x01\x12\b\n" +
	"\x04RRSP\x10\x02\x12\f\n" +
	"\bSTANDARD\x10\x03B-Z+github.com/sologenic/com-fs-user-model;userb\x06proto3"

var (
	file_user_fundings_proto_rawDescOnce sync.Once
	file_user_fundings_proto_rawDescData []byte
)

func file_user_fundings_proto_rawDescGZIP() []byte {
	file_user_fundings_proto_rawDescOnce.Do(func() {
		file_user_fundings_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_fundings_proto_rawDesc), len(file_user_fundings_proto_rawDesc)))
	})
	return file_user_fundings_proto_rawDescData
}

var file_user_fundings_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_user_fundings_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_user_fundings_proto_goTypes = []any{
	(SignerType)(0),                      // 0: user.SignerType
	(WalletType)(0),                      // 1: user.WalletType
	(*Wallet)(nil),                       // 2: user.Wallet
	(*BankAccount)(nil),                  // 3: user.BankAccount
	(*BrokerAccount)(nil),                // 4: user.BrokerAccount
	(order_properties.ClearingBroker)(0), // 5: orderproperties.ClearingBroker
}
var file_user_fundings_proto_depIdxs = []int32{
	1, // 0: user.Wallet.Type:type_name -> user.WalletType
	0, // 1: user.Wallet.SignerType:type_name -> user.SignerType
	5, // 2: user.BrokerAccount.Broker:type_name -> orderproperties.ClearingBroker
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_user_fundings_proto_init() }
func file_user_fundings_proto_init() {
	if File_user_fundings_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_fundings_proto_rawDesc), len(file_user_fundings_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_fundings_proto_goTypes,
		DependencyIndexes: file_user_fundings_proto_depIdxs,
		EnumInfos:         file_user_fundings_proto_enumTypes,
		MessageInfos:      file_user_fundings_proto_msgTypes,
	}.Build()
	File_user_fundings_proto = out.File
	file_user_fundings_proto_goTypes = nil
	file_user_fundings_proto_depIdxs = nil
}
