syntax = "proto3";

package user;

option go_package = "github.com/sologenic/com-fs-user-model;user";

import "buf/validate/validate.proto";

message Wallet {
    string Address = 1 [
        (buf.validate.field).string.pattern = "^(?:test)?core1[02-9ac-hj-np-z]{38}$"
    ];

    string Alias = 2 [
        (buf.validate.field).string = {
            min_len: 5,
            max_len: 32,
            pattern: "^[a-zA-Z][a-zA-Z0-9_]*[a-zA-Z0-9]$"
        }
    ];

    // Deprecated: we don't know what it is for and if we are going to use this in the future. Might be removed soon
    WalletType Type = 3;

    // Deprecated: we don't know what it is for and if we are going to use this in the future. Might be removed soon
    SignerType SignerType = 4;

    // List of organizations linked to this wallet address
    // Deprecated: doesn't fit into current user model, to be removed
    repeated string Organizations = 5 [
        (buf.validate.field).repeated = {
            max_items: 256,
            items: {
                string: {
                    uuid: true
                }
            }
        }
    ];
}

message BrokerAccount {
    string ID = 1 [
        (buf.validate.field).string = {
            min_len: 2,
            max_len: 128,
            pattern: "^[a-zA-Z0-9_-]+$"
        }
    ];

    BrokerType BrokerType = 2;

    reserved 3;
}

enum BrokerType {
    BROKER_TYPE_UNSPECIFIED = 0;
    BROKER_TYPE_ALPACA = 1;
}

// Deprecated: we don't know what it is for and if we are going to use this in the future. Might be removed soon
enum SignerType {
    NOT_USER_SIGNETTYPE = 0;
    MOBILE_APP = 1;
    BROWSER_LEAP = 2;
    BROWSER_COSMOSTATION = 3;
    BROWSER_KEPLR = 4;
}

// Deprecated: we don't know what it is for and if we are going to use this in the future. Might be removed soon
enum WalletType {
    NOT_USED_WALLETTYPE = 0;
    TFSA = 1;
    RRSP = 2;
    STANDARD = 3;
}