// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: user.proto

package user

import (
	com_fs_document_model "github.com/sologenic/com-fs-document-model"
	com_fs_order_model "github.com/sologenic/com-fs-order-model"
	com_fs_trade_profile_model "github.com/sologenic/com-fs-trade-profile-model"
	audit "github.com/sologenic/com-fs-utils-lib/models/audit"
	language "github.com/sologenic/com-fs-utils-lib/models/language"
	metadata "github.com/sologenic/com-fs-utils-lib/models/metadata"
	role "github.com/sologenic/com-fs-utils-lib/models/role"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KYCStatus int32

const (
	KYCStatus_KYC_STATUS_UNSPECIFIED KYCStatus = 0 // Default value, should not be used
	KYCStatus_KYC_STATUS_PENDING     KYCStatus = 1 // Inquiry created but not completed
	KYCStatus_KYC_STATUS_IN_REVIEW   KYCStatus = 2 // Inquiry submitted but under manual review
	KYCStatus_KYC_STATUS_APPROVED    KYCStatus = 3 // Inquiry completed and approved
	KYCStatus_KYC_STATUS_REJECTED    KYCStatus = 4 // Inquiry completed and explicitly rejected
	KYCStatus_KYC_STATUS_FAILED      KYCStatus = 5 // Inquiry failed due to an error (e.g., document mismatch, bad image quality)
	KYCStatus_KYC_STATUS_EXPIRED     KYCStatus = 6 // Inquiry expired (e.g., not completed in time)
)

// Enum value maps for KYCStatus.
var (
	KYCStatus_name = map[int32]string{
		0: "KYC_STATUS_UNSPECIFIED",
		1: "KYC_STATUS_PENDING",
		2: "KYC_STATUS_IN_REVIEW",
		3: "KYC_STATUS_APPROVED",
		4: "KYC_STATUS_REJECTED",
		5: "KYC_STATUS_FAILED",
		6: "KYC_STATUS_EXPIRED",
	}
	KYCStatus_value = map[string]int32{
		"KYC_STATUS_UNSPECIFIED": 0,
		"KYC_STATUS_PENDING":     1,
		"KYC_STATUS_IN_REVIEW":   2,
		"KYC_STATUS_APPROVED":    3,
		"KYC_STATUS_REJECTED":    4,
		"KYC_STATUS_FAILED":      5,
		"KYC_STATUS_EXPIRED":     6,
	}
)

func (x KYCStatus) Enum() *KYCStatus {
	p := new(KYCStatus)
	*p = x
	return p
}

func (x KYCStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KYCStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_user_proto_enumTypes[0].Descriptor()
}

func (KYCStatus) Type() protoreflect.EnumType {
	return &file_user_proto_enumTypes[0]
}

func (x KYCStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KYCStatus.Descriptor instead.
func (KYCStatus) EnumDescriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

type EmploymentType int32

const (
	EmploymentType_NOT_USED_EMPLOYMENTTYPE EmploymentType = 0
	EmploymentType_FULL_TIME               EmploymentType = 1
	EmploymentType_PART_TIME               EmploymentType = 2
	EmploymentType_CONTRACT                EmploymentType = 3
	EmploymentType_FREELANCE               EmploymentType = 4
	EmploymentType_SELF_EMPLOYED           EmploymentType = 5
	EmploymentType_INTERNSHIP              EmploymentType = 6
)

// Enum value maps for EmploymentType.
var (
	EmploymentType_name = map[int32]string{
		0: "NOT_USED_EMPLOYMENTTYPE",
		1: "FULL_TIME",
		2: "PART_TIME",
		3: "CONTRACT",
		4: "FREELANCE",
		5: "SELF_EMPLOYED",
		6: "INTERNSHIP",
	}
	EmploymentType_value = map[string]int32{
		"NOT_USED_EMPLOYMENTTYPE": 0,
		"FULL_TIME":               1,
		"PART_TIME":               2,
		"CONTRACT":                3,
		"FREELANCE":               4,
		"SELF_EMPLOYED":           5,
		"INTERNSHIP":              6,
	}
)

func (x EmploymentType) Enum() *EmploymentType {
	p := new(EmploymentType)
	*p = x
	return p
}

func (x EmploymentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EmploymentType) Descriptor() protoreflect.EnumDescriptor {
	return file_user_proto_enumTypes[1].Descriptor()
}

func (EmploymentType) Type() protoreflect.EnumType {
	return &file_user_proto_enumTypes[1]
}

func (x EmploymentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EmploymentType.Descriptor instead.
func (EmploymentType) EnumDescriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

type IncomeFrequency int32

const (
	IncomeFrequency_NOT_USED_INCOMEFREQUENCY IncomeFrequency = 0
	IncomeFrequency_HOURLY                   IncomeFrequency = 1
	IncomeFrequency_WEEKLY                   IncomeFrequency = 2
	IncomeFrequency_BI_WEEKLY                IncomeFrequency = 3
	IncomeFrequency_MONTHLY                  IncomeFrequency = 4
	IncomeFrequency_ANNUALLY                 IncomeFrequency = 5
)

// Enum value maps for IncomeFrequency.
var (
	IncomeFrequency_name = map[int32]string{
		0: "NOT_USED_INCOMEFREQUENCY",
		1: "HOURLY",
		2: "WEEKLY",
		3: "BI_WEEKLY",
		4: "MONTHLY",
		5: "ANNUALLY",
	}
	IncomeFrequency_value = map[string]int32{
		"NOT_USED_INCOMEFREQUENCY": 0,
		"HOURLY":                   1,
		"WEEKLY":                   2,
		"BI_WEEKLY":                3,
		"MONTHLY":                  4,
		"ANNUALLY":                 5,
	}
)

func (x IncomeFrequency) Enum() *IncomeFrequency {
	p := new(IncomeFrequency)
	*p = x
	return p
}

func (x IncomeFrequency) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IncomeFrequency) Descriptor() protoreflect.EnumDescriptor {
	return file_user_proto_enumTypes[2].Descriptor()
}

func (IncomeFrequency) Type() protoreflect.EnumType {
	return &file_user_proto_enumTypes[2]
}

func (x IncomeFrequency) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IncomeFrequency.Descriptor instead.
func (IncomeFrequency) EnumDescriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

type SignerType int32

const (
	SignerType_NOT_USER_SIGNETTYPE  SignerType = 0
	SignerType_MOBILE_APP           SignerType = 1
	SignerType_BROWSER_LEAP         SignerType = 2
	SignerType_BROWSER_COSMOSTATION SignerType = 3
	SignerType_BROWSER_KEPLR        SignerType = 4
)

// Enum value maps for SignerType.
var (
	SignerType_name = map[int32]string{
		0: "NOT_USER_SIGNETTYPE",
		1: "MOBILE_APP",
		2: "BROWSER_LEAP",
		3: "BROWSER_COSMOSTATION",
		4: "BROWSER_KEPLR",
	}
	SignerType_value = map[string]int32{
		"NOT_USER_SIGNETTYPE":  0,
		"MOBILE_APP":           1,
		"BROWSER_LEAP":         2,
		"BROWSER_COSMOSTATION": 3,
		"BROWSER_KEPLR":        4,
	}
)

func (x SignerType) Enum() *SignerType {
	p := new(SignerType)
	*p = x
	return p
}

func (x SignerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SignerType) Descriptor() protoreflect.EnumDescriptor {
	return file_user_proto_enumTypes[3].Descriptor()
}

func (SignerType) Type() protoreflect.EnumType {
	return &file_user_proto_enumTypes[3]
}

func (x SignerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SignerType.Descriptor instead.
func (SignerType) EnumDescriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

type UserStatus int32

const (
	UserStatus_NOT_USED_USERSTATUS UserStatus = 0
	UserStatus_ACTIVE              UserStatus = 1
	UserStatus_ADMIN_DEACTIVATED   UserStatus = 2
)

// Enum value maps for UserStatus.
var (
	UserStatus_name = map[int32]string{
		0: "NOT_USED_USERSTATUS",
		1: "ACTIVE",
		2: "ADMIN_DEACTIVATED",
	}
	UserStatus_value = map[string]int32{
		"NOT_USED_USERSTATUS": 0,
		"ACTIVE":              1,
		"ADMIN_DEACTIVATED":   2,
	}
)

func (x UserStatus) Enum() *UserStatus {
	p := new(UserStatus)
	*p = x
	return p
}

func (x UserStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_user_proto_enumTypes[4].Descriptor()
}

func (UserStatus) Type() protoreflect.EnumType {
	return &file_user_proto_enumTypes[4]
}

func (x UserStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserStatus.Descriptor instead.
func (UserStatus) EnumDescriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

type WalletType int32

const (
	WalletType_NOT_USED_WALLETTYPE WalletType = 0
	WalletType_TFSA                WalletType = 1
	WalletType_RRSP                WalletType = 2
	WalletType_STANDARD            WalletType = 3
)

// Enum value maps for WalletType.
var (
	WalletType_name = map[int32]string{
		0: "NOT_USED_WALLETTYPE",
		1: "TFSA",
		2: "RRSP",
		3: "STANDARD",
	}
	WalletType_value = map[string]int32{
		"NOT_USED_WALLETTYPE": 0,
		"TFSA":                1,
		"RRSP":                2,
		"STANDARD":            3,
	}
)

func (x WalletType) Enum() *WalletType {
	p := new(WalletType)
	*p = x
	return p
}

func (x WalletType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WalletType) Descriptor() protoreflect.EnumDescriptor {
	return file_user_proto_enumTypes[5].Descriptor()
}

func (WalletType) Type() protoreflect.EnumType {
	return &file_user_proto_enumTypes[5]
}

func (x WalletType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WalletType.Descriptor instead.
func (WalletType) EnumDescriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

type SocialType int32

const (
	SocialType_NOT_USED_SOCIALTYPE SocialType = 0
	SocialType_WEBSITE             SocialType = 1
	SocialType_GITHUB              SocialType = 2
	SocialType_REDDIT              SocialType = 3
	SocialType_DISCORD             SocialType = 4
	SocialType_TWITTER             SocialType = 5
	SocialType_FACEBOOK            SocialType = 6
	SocialType_TELEGRAM            SocialType = 7
	SocialType_INSTAGRAM           SocialType = 8
	SocialType_LINKEDIN            SocialType = 9
)

// Enum value maps for SocialType.
var (
	SocialType_name = map[int32]string{
		0: "NOT_USED_SOCIALTYPE",
		1: "WEBSITE",
		2: "GITHUB",
		3: "REDDIT",
		4: "DISCORD",
		5: "TWITTER",
		6: "FACEBOOK",
		7: "TELEGRAM",
		8: "INSTAGRAM",
		9: "LINKEDIN",
	}
	SocialType_value = map[string]int32{
		"NOT_USED_SOCIALTYPE": 0,
		"WEBSITE":             1,
		"GITHUB":              2,
		"REDDIT":              3,
		"DISCORD":             4,
		"TWITTER":             5,
		"FACEBOOK":            6,
		"TELEGRAM":            7,
		"INSTAGRAM":           8,
		"LINKEDIN":            9,
	}
)

func (x SocialType) Enum() *SocialType {
	p := new(SocialType)
	*p = x
	return p
}

func (x SocialType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SocialType) Descriptor() protoreflect.EnumDescriptor {
	return file_user_proto_enumTypes[6].Descriptor()
}

func (SocialType) Type() protoreflect.EnumType {
	return &file_user_proto_enumTypes[6]
}

func (x SocialType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SocialType.Descriptor instead.
func (SocialType) EnumDescriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

type LiquidationImportance int32

const (
	LiquidationImportance_VERY_IMPORTANT     LiquidationImportance = 0
	LiquidationImportance_SOMEWHAT_IMPORTANT LiquidationImportance = 1
	LiquidationImportance_NOT_IMPORTANT      LiquidationImportance = 2
	LiquidationImportance_NO_PREFERENCE      LiquidationImportance = 3
)

// Enum value maps for LiquidationImportance.
var (
	LiquidationImportance_name = map[int32]string{
		0: "VERY_IMPORTANT",
		1: "SOMEWHAT_IMPORTANT",
		2: "NOT_IMPORTANT",
		3: "NO_PREFERENCE",
	}
	LiquidationImportance_value = map[string]int32{
		"VERY_IMPORTANT":     0,
		"SOMEWHAT_IMPORTANT": 1,
		"NOT_IMPORTANT":      2,
		"NO_PREFERENCE":      3,
	}
)

func (x LiquidationImportance) Enum() *LiquidationImportance {
	p := new(LiquidationImportance)
	*p = x
	return p
}

func (x LiquidationImportance) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LiquidationImportance) Descriptor() protoreflect.EnumDescriptor {
	return file_user_proto_enumTypes[7].Descriptor()
}

func (LiquidationImportance) Type() protoreflect.EnumType {
	return &file_user_proto_enumTypes[7]
}

func (x LiquidationImportance) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LiquidationImportance.Descriptor instead.
func (LiquidationImportance) EnumDescriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

type RiskTolerance int32

const (
	RiskTolerance_CONSERVATIVE            RiskTolerance = 0
	RiskTolerance_MODERATELY_CONSERVATIVE RiskTolerance = 1
	RiskTolerance_MODERATE                RiskTolerance = 2
	RiskTolerance_MODERATELY_AGGRESSIVE   RiskTolerance = 3
	RiskTolerance_SIGNIFICANT_RISK        RiskTolerance = 4
)

// Enum value maps for RiskTolerance.
var (
	RiskTolerance_name = map[int32]string{
		0: "CONSERVATIVE",
		1: "MODERATELY_CONSERVATIVE",
		2: "MODERATE",
		3: "MODERATELY_AGGRESSIVE",
		4: "SIGNIFICANT_RISK",
	}
	RiskTolerance_value = map[string]int32{
		"CONSERVATIVE":            0,
		"MODERATELY_CONSERVATIVE": 1,
		"MODERATE":                2,
		"MODERATELY_AGGRESSIVE":   3,
		"SIGNIFICANT_RISK":        4,
	}
)

func (x RiskTolerance) Enum() *RiskTolerance {
	p := new(RiskTolerance)
	*p = x
	return p
}

func (x RiskTolerance) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RiskTolerance) Descriptor() protoreflect.EnumDescriptor {
	return file_user_proto_enumTypes[8].Descriptor()
}

func (RiskTolerance) Type() protoreflect.EnumType {
	return &file_user_proto_enumTypes[8]
}

func (x RiskTolerance) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RiskTolerance.Descriptor instead.
func (RiskTolerance) EnumDescriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{8}
}

type InvestmentObjective int32

const (
	InvestmentObjective_INCOME                        InvestmentObjective = 0
	InvestmentObjective_BALANCED                      InvestmentObjective = 1
	InvestmentObjective_GROWTH_AND_INCOME             InvestmentObjective = 2
	InvestmentObjective_SAFE_LONG_TERM_GROWTH         InvestmentObjective = 3
	InvestmentObjective_GREATER_RISK_LONG_TERM_GROWTH InvestmentObjective = 4
	InvestmentObjective_SPECULATION                   InvestmentObjective = 5
)

// Enum value maps for InvestmentObjective.
var (
	InvestmentObjective_name = map[int32]string{
		0: "INCOME",
		1: "BALANCED",
		2: "GROWTH_AND_INCOME",
		3: "SAFE_LONG_TERM_GROWTH",
		4: "GREATER_RISK_LONG_TERM_GROWTH",
		5: "SPECULATION",
	}
	InvestmentObjective_value = map[string]int32{
		"INCOME":                        0,
		"BALANCED":                      1,
		"GROWTH_AND_INCOME":             2,
		"SAFE_LONG_TERM_GROWTH":         3,
		"GREATER_RISK_LONG_TERM_GROWTH": 4,
		"SPECULATION":                   5,
	}
)

func (x InvestmentObjective) Enum() *InvestmentObjective {
	p := new(InvestmentObjective)
	*p = x
	return p
}

func (x InvestmentObjective) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InvestmentObjective) Descriptor() protoreflect.EnumDescriptor {
	return file_user_proto_enumTypes[9].Descriptor()
}

func (InvestmentObjective) Type() protoreflect.EnumType {
	return &file_user_proto_enumTypes[9]
}

func (x InvestmentObjective) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InvestmentObjective.Descriptor instead.
func (InvestmentObjective) EnumDescriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{9}
}

type IDNumber struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	IssuingCountry       string                 `protobuf:"bytes,1,opt,name=IssuingCountry,proto3" json:"IssuingCountry,omitempty"`
	IdentificationClass  string                 `protobuf:"bytes,2,opt,name=IdentificationClass,proto3" json:"IdentificationClass,omitempty"`
	IdentificationNumber string                 `protobuf:"bytes,3,opt,name=IdentificationNumber,proto3" json:"IdentificationNumber,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *IDNumber) Reset() {
	*x = IDNumber{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IDNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDNumber) ProtoMessage() {}

func (x *IDNumber) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDNumber.ProtoReflect.Descriptor instead.
func (*IDNumber) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *IDNumber) GetIssuingCountry() string {
	if x != nil {
		return x.IssuingCountry
	}
	return ""
}

func (x *IDNumber) GetIdentificationClass() string {
	if x != nil {
		return x.IdentificationClass
	}
	return ""
}

func (x *IDNumber) GetIdentificationNumber() string {
	if x != nil {
		return x.IdentificationNumber
	}
	return ""
}

type UserKYCDetails struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Birthdate            string                 `protobuf:"bytes,1,opt,name=Birthdate,proto3" json:"Birthdate,omitempty"`
	PhoneNumber          string                 `protobuf:"bytes,2,opt,name=PhoneNumber,proto3" json:"PhoneNumber,omitempty"`
	EmailAddress         string                 `protobuf:"bytes,3,opt,name=EmailAddress,proto3" json:"EmailAddress,omitempty"`
	AddressStreet1       string                 `protobuf:"bytes,4,opt,name=AddressStreet1,proto3" json:"AddressStreet1,omitempty"`
	AddressStreet2       string                 `protobuf:"bytes,5,opt,name=AddressStreet2,proto3" json:"AddressStreet2,omitempty"`
	AddressCity          string                 `protobuf:"bytes,6,opt,name=AddressCity,proto3" json:"AddressCity,omitempty"`
	AddressSubdivision   string                 `protobuf:"bytes,7,opt,name=AddressSubdivision,proto3" json:"AddressSubdivision,omitempty"`
	AddressPostalCode    string                 `protobuf:"bytes,8,opt,name=AddressPostalCode,proto3" json:"AddressPostalCode,omitempty"`
	CountryCode          string                 `protobuf:"bytes,9,opt,name=CountryCode,proto3" json:"CountryCode,omitempty"`
	SocialSecurityNumber string                 `protobuf:"bytes,10,opt,name=SocialSecurityNumber,proto3" json:"SocialSecurityNumber,omitempty"`
	IdentificationNumber string                 `protobuf:"bytes,11,opt,name=IdentificationNumber,proto3" json:"IdentificationNumber,omitempty"`
	FirstName            string                 `protobuf:"bytes,12,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName             string                 `protobuf:"bytes,13,opt,name=LastName,proto3" json:"LastName,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UserKYCDetails) Reset() {
	*x = UserKYCDetails{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserKYCDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserKYCDetails) ProtoMessage() {}

func (x *UserKYCDetails) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserKYCDetails.ProtoReflect.Descriptor instead.
func (*UserKYCDetails) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserKYCDetails) GetBirthdate() string {
	if x != nil {
		return x.Birthdate
	}
	return ""
}

func (x *UserKYCDetails) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *UserKYCDetails) GetEmailAddress() string {
	if x != nil {
		return x.EmailAddress
	}
	return ""
}

func (x *UserKYCDetails) GetAddressStreet1() string {
	if x != nil {
		return x.AddressStreet1
	}
	return ""
}

func (x *UserKYCDetails) GetAddressStreet2() string {
	if x != nil {
		return x.AddressStreet2
	}
	return ""
}

func (x *UserKYCDetails) GetAddressCity() string {
	if x != nil {
		return x.AddressCity
	}
	return ""
}

func (x *UserKYCDetails) GetAddressSubdivision() string {
	if x != nil {
		return x.AddressSubdivision
	}
	return ""
}

func (x *UserKYCDetails) GetAddressPostalCode() string {
	if x != nil {
		return x.AddressPostalCode
	}
	return ""
}

func (x *UserKYCDetails) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *UserKYCDetails) GetSocialSecurityNumber() string {
	if x != nil {
		return x.SocialSecurityNumber
	}
	return ""
}

func (x *UserKYCDetails) GetIdentificationNumber() string {
	if x != nil {
		return x.IdentificationNumber
	}
	return ""
}

func (x *UserKYCDetails) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UserKYCDetails) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

type UserDetails struct {
	state                  protoimpl.MessageState                          `protogen:"open.v1"`
	UserID                 string                                          `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"` // email address used for firebase authentication
	FirstName              string                                          `protobuf:"bytes,2,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName               string                                          `protobuf:"bytes,3,opt,name=LastName,proto3" json:"LastName,omitempty"`
	Address                string                                          `protobuf:"bytes,4,opt,name=Address,proto3" json:"Address,omitempty"`
	Avatar                 string                                          `protobuf:"bytes,5,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
	Alias                  string                                          `protobuf:"bytes,6,opt,name=Alias,proto3" json:"Alias,omitempty"` // "Nickname"
	Description            string                                          `protobuf:"bytes,7,opt,name=Description,proto3" json:"Description,omitempty"`
	Status                 UserStatus                                      `protobuf:"varint,8,opt,name=Status,proto3,enum=user.UserStatus" json:"Status,omitempty"`
	Wallets                []*Wallet                                       `protobuf:"bytes,9,rep,name=Wallets,proto3" json:"Wallets,omitempty"`
	Socials                []*Social                                       `protobuf:"bytes,10,rep,name=Socials,proto3" json:"Socials,omitempty"`
	Language               language.Lang                                   `protobuf:"varint,11,opt,name=Language,proto3,enum=language.Lang" json:"Language,omitempty"`
	ExternalUserID         string                                          `protobuf:"bytes,12,opt,name=ExternalUserID,proto3" json:"ExternalUserID,omitempty"` // UUID for the external user identifier in the KYC provider
	OrganizationID         string                                          `protobuf:"bytes,13,opt,name=OrganizationID,proto3" json:"OrganizationID,omitempty"` // UUID
	Employment             *Employment                                     `protobuf:"bytes,14,opt,name=Employment,proto3,oneof" json:"Employment,omitempty"`
	Role                   role.Role                                       `protobuf:"varint,15,opt,name=Role,proto3,enum=role.Role" json:"Role,omitempty"` // A retail user will always have a role of "NORMAL_USER"
	TradeProfile           *com_fs_trade_profile_model.TradeProfileDetails `protobuf:"bytes,16,opt,name=TradeProfile,proto3" json:"TradeProfile,omitempty"` // Trade profile details
	KYCInquiries           []string                                        `protobuf:"bytes,17,rep,name=KYCInquiries,proto3" json:"KYCInquiries,omitempty"` // Array of inquiry ID's
	KYCDetails             *UserKYCDetails                                 `protobuf:"bytes,18,opt,name=KYCDetails,proto3" json:"KYCDetails,omitempty"`
	UserDocumentCompliance *com_fs_document_model.UserDocumentCompliance   `protobuf:"bytes,19,opt,name=UserDocumentCompliance,proto3" json:"UserDocumentCompliance,omitempty"`
	KYCStatus              KYCStatus                                       `protobuf:"varint,20,opt,name=KYCStatus,proto3,enum=user.KYCStatus" json:"KYCStatus,omitempty"` // Status of KYC verification, e.g., PENDING, APPROVED, REJECTED
	UserTradeProfile       *com_fs_trade_profile_model.UserTradeProfile    `protobuf:"bytes,21,opt,name=UserTradeProfile,proto3" json:"UserTradeProfile,omitempty"`
	ComplianceQuestions    []*ComplianceQuestions                          `protobuf:"bytes,22,rep,name=ComplianceQuestions,proto3" json:"ComplianceQuestions,omitempty"`
	BrokerAccounts         []*BrokerAccount                                `protobuf:"bytes,23,rep,name=BrokerAccounts,proto3" json:"BrokerAccounts,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UserDetails) Reset() {
	*x = UserDetails{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDetails) ProtoMessage() {}

func (x *UserDetails) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDetails.ProtoReflect.Descriptor instead.
func (*UserDetails) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserDetails) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *UserDetails) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UserDetails) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UserDetails) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UserDetails) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserDetails) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *UserDetails) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UserDetails) GetStatus() UserStatus {
	if x != nil {
		return x.Status
	}
	return UserStatus_NOT_USED_USERSTATUS
}

func (x *UserDetails) GetWallets() []*Wallet {
	if x != nil {
		return x.Wallets
	}
	return nil
}

func (x *UserDetails) GetSocials() []*Social {
	if x != nil {
		return x.Socials
	}
	return nil
}

func (x *UserDetails) GetLanguage() language.Lang {
	if x != nil {
		return x.Language
	}
	return language.Lang(0)
}

func (x *UserDetails) GetExternalUserID() string {
	if x != nil {
		return x.ExternalUserID
	}
	return ""
}

func (x *UserDetails) GetOrganizationID() string {
	if x != nil {
		return x.OrganizationID
	}
	return ""
}

func (x *UserDetails) GetEmployment() *Employment {
	if x != nil {
		return x.Employment
	}
	return nil
}

func (x *UserDetails) GetRole() role.Role {
	if x != nil {
		return x.Role
	}
	return role.Role(0)
}

func (x *UserDetails) GetTradeProfile() *com_fs_trade_profile_model.TradeProfileDetails {
	if x != nil {
		return x.TradeProfile
	}
	return nil
}

func (x *UserDetails) GetKYCInquiries() []string {
	if x != nil {
		return x.KYCInquiries
	}
	return nil
}

func (x *UserDetails) GetKYCDetails() *UserKYCDetails {
	if x != nil {
		return x.KYCDetails
	}
	return nil
}

func (x *UserDetails) GetUserDocumentCompliance() *com_fs_document_model.UserDocumentCompliance {
	if x != nil {
		return x.UserDocumentCompliance
	}
	return nil
}

func (x *UserDetails) GetKYCStatus() KYCStatus {
	if x != nil {
		return x.KYCStatus
	}
	return KYCStatus_KYC_STATUS_UNSPECIFIED
}

func (x *UserDetails) GetUserTradeProfile() *com_fs_trade_profile_model.UserTradeProfile {
	if x != nil {
		return x.UserTradeProfile
	}
	return nil
}

func (x *UserDetails) GetComplianceQuestions() []*ComplianceQuestions {
	if x != nil {
		return x.ComplianceQuestions
	}
	return nil
}

func (x *UserDetails) GetBrokerAccounts() []*BrokerAccount {
	if x != nil {
		return x.BrokerAccounts
	}
	return nil
}

// TODO: to be verified when more information is available
type Employment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmployerName  string                 `protobuf:"bytes,1,opt,name=EmployerName,proto3" json:"EmployerName,omitempty"`
	JobTitle      string                 `protobuf:"bytes,2,opt,name=JobTitle,proto3" json:"JobTitle,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=StartDate,proto3" json:"StartDate,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=EndDate,proto3" json:"EndDate,omitempty"` // Empty if still employed
	Type          EmploymentType         `protobuf:"varint,5,opt,name=Type,proto3,enum=user.EmploymentType" json:"Type,omitempty"`
	Industry      *string                `protobuf:"bytes,6,opt,name=Industry,proto3,oneof" json:"Industry,omitempty"`
	Income        *Income                `protobuf:"bytes,7,opt,name=Income,proto3" json:"Income,omitempty"`
	Contact       *EmployerContact       `protobuf:"bytes,8,opt,name=Contact,proto3" json:"Contact,omitempty"`
	IsVerified    bool                   `protobuf:"varint,9,opt,name=IsVerified,proto3" json:"IsVerified,omitempty"`
	VerifiedAt    string                 `protobuf:"bytes,10,opt,name=VerifiedAt,proto3" json:"VerifiedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Employment) Reset() {
	*x = Employment{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Employment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Employment) ProtoMessage() {}

func (x *Employment) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Employment.ProtoReflect.Descriptor instead.
func (*Employment) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *Employment) GetEmployerName() string {
	if x != nil {
		return x.EmployerName
	}
	return ""
}

func (x *Employment) GetJobTitle() string {
	if x != nil {
		return x.JobTitle
	}
	return ""
}

func (x *Employment) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *Employment) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *Employment) GetType() EmploymentType {
	if x != nil {
		return x.Type
	}
	return EmploymentType_NOT_USED_EMPLOYMENTTYPE
}

func (x *Employment) GetIndustry() string {
	if x != nil && x.Industry != nil {
		return *x.Industry
	}
	return ""
}

func (x *Employment) GetIncome() *Income {
	if x != nil {
		return x.Income
	}
	return nil
}

func (x *Employment) GetContact() *EmployerContact {
	if x != nil {
		return x.Contact
	}
	return nil
}

func (x *Employment) GetIsVerified() bool {
	if x != nil {
		return x.IsVerified
	}
	return false
}

func (x *Employment) GetVerifiedAt() string {
	if x != nil {
		return x.VerifiedAt
	}
	return ""
}

type Income struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        float32                `protobuf:"fixed32,1,opt,name=Amount,proto3" json:"Amount,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=Currency,proto3" json:"Currency,omitempty"`
	Frequency     IncomeFrequency        `protobuf:"varint,3,opt,name=Frequency,proto3,enum=user.IncomeFrequency" json:"Frequency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Income) Reset() {
	*x = Income{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Income) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Income) ProtoMessage() {}

func (x *Income) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Income.ProtoReflect.Descriptor instead.
func (*Income) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *Income) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Income) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Income) GetFrequency() IncomeFrequency {
	if x != nil {
		return x.Frequency
	}
	return IncomeFrequency_NOT_USED_INCOMEFREQUENCY
}

type EmployerContact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=Phone,proto3" json:"Phone,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=Address,proto3" json:"Address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmployerContact) Reset() {
	*x = EmployerContact{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmployerContact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployerContact) ProtoMessage() {}

func (x *EmployerContact) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployerContact.ProtoReflect.Descriptor instead.
func (*EmployerContact) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *EmployerContact) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EmployerContact) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *EmployerContact) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *EmployerContact) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserDetails           `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	MetaData      *metadata.MetaData     `protobuf:"bytes,2,opt,name=MetaData,proto3" json:"MetaData,omitempty"`
	Audit         *audit.Audit           `protobuf:"bytes,3,opt,name=Audit,proto3" json:"Audit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *User) GetUser() *UserDetails {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *User) GetMetaData() *metadata.MetaData {
	if x != nil {
		return x.MetaData
	}
	return nil
}

func (x *User) GetAudit() *audit.Audit {
	if x != nil {
		return x.Audit
	}
	return nil
}

type UserID struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserID         string                 `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	OrganizationID string                 `protobuf:"bytes,2,opt,name=OrganizationID,proto3" json:"OrganizationID,omitempty"`
	Network        *metadata.Network      `protobuf:"varint,3,opt,name=Network,proto3,enum=metadata.Network,oneof" json:"Network,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserID) Reset() {
	*x = UserID{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserID) ProtoMessage() {}

func (x *UserID) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserID.ProtoReflect.Descriptor instead.
func (*UserID) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

func (x *UserID) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *UserID) GetOrganizationID() string {
	if x != nil {
		return x.OrganizationID
	}
	return ""
}

func (x *UserID) GetNetwork() metadata.Network {
	if x != nil && x.Network != nil {
		return *x.Network
	}
	return metadata.Network(0)
}

type Social struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	URL           string                 `protobuf:"bytes,1,opt,name=URL,proto3" json:"URL,omitempty"`
	Type          SocialType             `protobuf:"varint,2,opt,name=Type,proto3,enum=user.SocialType" json:"Type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Social) Reset() {
	*x = Social{}
	mi := &file_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Social) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Social) ProtoMessage() {}

func (x *Social) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Social.ProtoReflect.Descriptor instead.
func (*Social) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{8}
}

func (x *Social) GetURL() string {
	if x != nil {
		return x.URL
	}
	return ""
}

func (x *Social) GetType() SocialType {
	if x != nil {
		return x.Type
	}
	return SocialType_NOT_USED_SOCIALTYPE
}

type Wallet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	Alias         string                 `protobuf:"bytes,2,opt,name=Alias,proto3" json:"Alias,omitempty"`
	Type          WalletType             `protobuf:"varint,3,opt,name=Type,proto3,enum=user.WalletType" json:"Type,omitempty"`
	SignerType    SignerType             `protobuf:"varint,4,opt,name=SignerType,proto3,enum=user.SignerType" json:"SignerType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wallet) Reset() {
	*x = Wallet{}
	mi := &file_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wallet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wallet) ProtoMessage() {}

func (x *Wallet) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wallet.ProtoReflect.Descriptor instead.
func (*Wallet) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{9}
}

func (x *Wallet) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Wallet) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *Wallet) GetType() WalletType {
	if x != nil {
		return x.Type
	}
	return WalletType_NOT_USED_WALLETTYPE
}

func (x *Wallet) GetSignerType() SignerType {
	if x != nil {
		return x.SignerType
	}
	return SignerType_NOT_USER_SIGNETTYPE
}

type UserList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=Users,proto3" json:"Users,omitempty"`
	Offset        *int32                 `protobuf:"varint,2,opt,name=Offset,proto3,oneof" json:"Offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserList) Reset() {
	*x = UserList{}
	mi := &file_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserList) ProtoMessage() {}

func (x *UserList) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserList.ProtoReflect.Descriptor instead.
func (*UserList) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{10}
}

func (x *UserList) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *UserList) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

type StatusMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserID         string                 `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	OrganizationID string                 `protobuf:"bytes,2,opt,name=OrganizationID,proto3" json:"OrganizationID,omitempty"`
	Status         UserStatus             `protobuf:"varint,3,opt,name=Status,proto3,enum=user.UserStatus" json:"Status,omitempty"`
	Network        *metadata.Network      `protobuf:"varint,4,opt,name=Network,proto3,enum=metadata.Network,oneof" json:"Network,omitempty"`
	Audit          *audit.Audit           `protobuf:"bytes,5,opt,name=Audit,proto3" json:"Audit,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StatusMessage) Reset() {
	*x = StatusMessage{}
	mi := &file_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusMessage) ProtoMessage() {}

func (x *StatusMessage) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusMessage.ProtoReflect.Descriptor instead.
func (*StatusMessage) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{11}
}

func (x *StatusMessage) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *StatusMessage) GetOrganizationID() string {
	if x != nil {
		return x.OrganizationID
	}
	return ""
}

func (x *StatusMessage) GetStatus() UserStatus {
	if x != nil {
		return x.Status
	}
	return UserStatus_NOT_USED_USERSTATUS
}

func (x *StatusMessage) GetNetwork() metadata.Network {
	if x != nil && x.Network != nil {
		return *x.Network
	}
	return metadata.Network(0)
}

func (x *StatusMessage) GetAudit() *audit.Audit {
	if x != nil {
		return x.Audit
	}
	return nil
}

type Filter struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserIDs         []string               `protobuf:"bytes,1,rep,name=UserIDs,proto3" json:"UserIDs,omitempty"`
	Network         *metadata.Network      `protobuf:"varint,2,opt,name=Network,proto3,enum=metadata.Network,oneof" json:"Network,omitempty"`
	OrganizationID  string                 `protobuf:"bytes,3,opt,name=OrganizationID,proto3" json:"OrganizationID,omitempty"`
	Offset          *int32                 `protobuf:"varint,4,opt,name=Offset,proto3,oneof" json:"Offset,omitempty"`
	Limit           *int32                 `protobuf:"varint,5,opt,name=Limit,proto3,oneof" json:"Limit,omitempty"`
	InquiryID       *string                `protobuf:"bytes,6,opt,name=InquiryID,proto3,oneof" json:"InquiryID,omitempty"`
	Status          *UserStatus            `protobuf:"varint,7,opt,name=Status,proto3,enum=user.UserStatus,oneof" json:"Status,omitempty"`
	ExternalUserIDs []string               `protobuf:"bytes,8,rep,name=ExternalUserIDs,proto3" json:"ExternalUserIDs,omitempty"`
	WalletAddress   *string                `protobuf:"bytes,9,opt,name=WalletAddress,proto3,oneof" json:"WalletAddress,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{12}
}

func (x *Filter) GetUserIDs() []string {
	if x != nil {
		return x.UserIDs
	}
	return nil
}

func (x *Filter) GetNetwork() metadata.Network {
	if x != nil && x.Network != nil {
		return *x.Network
	}
	return metadata.Network(0)
}

func (x *Filter) GetOrganizationID() string {
	if x != nil {
		return x.OrganizationID
	}
	return ""
}

func (x *Filter) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *Filter) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *Filter) GetInquiryID() string {
	if x != nil && x.InquiryID != nil {
		return *x.InquiryID
	}
	return ""
}

func (x *Filter) GetStatus() UserStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return UserStatus_NOT_USED_USERSTATUS
}

func (x *Filter) GetExternalUserIDs() []string {
	if x != nil {
		return x.ExternalUserIDs
	}
	return nil
}

func (x *Filter) GetWalletAddress() string {
	if x != nil && x.WalletAddress != nil {
		return *x.WalletAddress
	}
	return ""
}

// This model is open to having multiple questionaires with regards to compliance like MiFID, etc.
type ComplianceQuestions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	USA           *USA                   `protobuf:"bytes,1,opt,name=USA,proto3,oneof" json:"USA,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComplianceQuestions) Reset() {
	*x = ComplianceQuestions{}
	mi := &file_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComplianceQuestions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComplianceQuestions) ProtoMessage() {}

func (x *ComplianceQuestions) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComplianceQuestions.ProtoReflect.Descriptor instead.
func (*ComplianceQuestions) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{13}
}

func (x *ComplianceQuestions) GetUSA() *USA {
	if x != nil {
		return x.USA
	}
	return nil
}

type USA struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	RecordedAt           *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=RecordedAt,proto3" json:"RecordedAt,omitempty"`
	YearsExperience      int64                  `protobuf:"varint,2,opt,name=YearsExperience,proto3" json:"YearsExperience,omitempty"`
	AnnualIncome         int64                  `protobuf:"varint,3,opt,name=AnnualIncome,proto3" json:"AnnualIncome,omitempty"`
	NetWorth             int64                  `protobuf:"varint,4,opt,name=NetWorth,proto3" json:"NetWorth,omitempty"`
	ConversionImportance LiquidationImportance  `protobuf:"varint,5,opt,name=ConversionImportance,proto3,enum=user.LiquidationImportance" json:"ConversionImportance,omitempty"`
	Tolerance            RiskTolerance          `protobuf:"varint,6,opt,name=Tolerance,proto3,enum=user.RiskTolerance" json:"Tolerance,omitempty"`
	Objective            InvestmentObjective    `protobuf:"varint,7,opt,name=Objective,proto3,enum=user.InvestmentObjective" json:"Objective,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *USA) Reset() {
	*x = USA{}
	mi := &file_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *USA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*USA) ProtoMessage() {}

func (x *USA) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use USA.ProtoReflect.Descriptor instead.
func (*USA) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{14}
}

func (x *USA) GetRecordedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RecordedAt
	}
	return nil
}

func (x *USA) GetYearsExperience() int64 {
	if x != nil {
		return x.YearsExperience
	}
	return 0
}

func (x *USA) GetAnnualIncome() int64 {
	if x != nil {
		return x.AnnualIncome
	}
	return 0
}

func (x *USA) GetNetWorth() int64 {
	if x != nil {
		return x.NetWorth
	}
	return 0
}

func (x *USA) GetConversionImportance() LiquidationImportance {
	if x != nil {
		return x.ConversionImportance
	}
	return LiquidationImportance_VERY_IMPORTANT
}

func (x *USA) GetTolerance() RiskTolerance {
	if x != nil {
		return x.Tolerance
	}
	return RiskTolerance_CONSERVATIVE
}

func (x *USA) GetObjective() InvestmentObjective {
	if x != nil {
		return x.Objective
	}
	return InvestmentObjective_INCOME
}

type BrokerAccount struct {
	state          protoimpl.MessageState            `protogen:"open.v1"`
	AccountID      string                            `protobuf:"bytes,1,opt,name=AccountID,proto3" json:"AccountID,omitempty"`                      // user's identifier in the broker account
	Broker         com_fs_order_model.ClearingBroker `protobuf:"varint,2,opt,name=Broker,proto3,enum=order.ClearingBroker" json:"Broker,omitempty"` // "RQD", etc.
	OrganizationID string                            `protobuf:"bytes,3,opt,name=OrganizationID,proto3" json:"OrganizationID,omitempty"`            // broker identifier
	Profiles       []string                          `protobuf:"bytes,4,rep,name=Profiles,proto3" json:"Profiles,omitempty"`                        // bank account profiles for the broker account
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BrokerAccount) Reset() {
	*x = BrokerAccount{}
	mi := &file_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrokerAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrokerAccount) ProtoMessage() {}

func (x *BrokerAccount) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrokerAccount.ProtoReflect.Descriptor instead.
func (*BrokerAccount) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{15}
}

func (x *BrokerAccount) GetAccountID() string {
	if x != nil {
		return x.AccountID
	}
	return ""
}

func (x *BrokerAccount) GetBroker() com_fs_order_model.ClearingBroker {
	if x != nil {
		return x.Broker
	}
	return com_fs_order_model.ClearingBroker(0)
}

func (x *BrokerAccount) GetOrganizationID() string {
	if x != nil {
		return x.OrganizationID
	}
	return ""
}

func (x *BrokerAccount) GetProfiles() []string {
	if x != nil {
		return x.Profiles
	}
	return nil
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x04user\x1a\x1fgoogle/protobuf/timestamp.proto\x1a9sologenic/com-fs-utils-lib/models/metadata/metadata.proto\x1a3sologenic/com-fs-utils-lib/models/audit/audit.proto\x1a1sologenic/com-fs-utils-lib/models/role/role.proto\x1a9sologenic/com-fs-utils-lib/models/language/language.proto\x1a7sologenic/com-fs-trade-profile-model/tradeprofile.proto\x1a.sologenic/com-fs-document-model/document.proto\x1a)sologenic/com-fs-order-model/broker.proto\"\x98\x01\n" +
	"\bIDNumber\x12&\n" +
	"\x0eIssuingCountry\x18\x01 \x01(\tR\x0eIssuingCountry\x120\n" +
	"\x13IdentificationClass\x18\x02 \x01(\tR\x13IdentificationClass\x122\n" +
	"\x14IdentificationNumber\x18\x03 \x01(\tR\x14IdentificationNumber\"\x88\x04\n" +
	"\x0eUserKYCDetails\x12\x1c\n" +
	"\tBirthdate\x18\x01 \x01(\tR\tBirthdate\x12 \n" +
	"\vPhoneNumber\x18\x02 \x01(\tR\vPhoneNumber\x12\"\n" +
	"\fEmailAddress\x18\x03 \x01(\tR\fEmailAddress\x12&\n" +
	"\x0eAddressStreet1\x18\x04 \x01(\tR\x0eAddressStreet1\x12&\n" +
	"\x0eAddressStreet2\x18\x05 \x01(\tR\x0eAddressStreet2\x12 \n" +
	"\vAddressCity\x18\x06 \x01(\tR\vAddressCity\x12.\n" +
	"\x12AddressSubdivision\x18\a \x01(\tR\x12AddressSubdivision\x12,\n" +
	"\x11AddressPostalCode\x18\b \x01(\tR\x11AddressPostalCode\x12 \n" +
	"\vCountryCode\x18\t \x01(\tR\vCountryCode\x122\n" +
	"\x14SocialSecurityNumber\x18\n" +
	" \x01(\tR\x14SocialSecurityNumber\x122\n" +
	"\x14IdentificationNumber\x18\v \x01(\tR\x14IdentificationNumber\x12\x1c\n" +
	"\tFirstName\x18\f \x01(\tR\tFirstName\x12\x1a\n" +
	"\bLastName\x18\r \x01(\tR\bLastName\"\xa5\b\n" +
	"\vUserDetails\x12\x16\n" +
	"\x06UserID\x18\x01 \x01(\tR\x06UserID\x12\x1c\n" +
	"\tFirstName\x18\x02 \x01(\tR\tFirstName\x12\x1a\n" +
	"\bLastName\x18\x03 \x01(\tR\bLastName\x12\x18\n" +
	"\aAddress\x18\x04 \x01(\tR\aAddress\x12\x16\n" +
	"\x06Avatar\x18\x05 \x01(\tR\x06Avatar\x12\x14\n" +
	"\x05Alias\x18\x06 \x01(\tR\x05Alias\x12 \n" +
	"\vDescription\x18\a \x01(\tR\vDescription\x12(\n" +
	"\x06Status\x18\b \x01(\x0e2\x10.user.UserStatusR\x06Status\x12&\n" +
	"\aWallets\x18\t \x03(\v2\f.user.WalletR\aWallets\x12&\n" +
	"\aSocials\x18\n" +
	" \x03(\v2\f.user.SocialR\aSocials\x12*\n" +
	"\bLanguage\x18\v \x01(\x0e2\x0e.language.LangR\bLanguage\x12&\n" +
	"\x0eExternalUserID\x18\f \x01(\tR\x0eExternalUserID\x12&\n" +
	"\x0eOrganizationID\x18\r \x01(\tR\x0eOrganizationID\x125\n" +
	"\n" +
	"Employment\x18\x0e \x01(\v2\x10.user.EmploymentH\x00R\n" +
	"Employment\x88\x01\x01\x12\x1e\n" +
	"\x04Role\x18\x0f \x01(\x0e2\n" +
	".role.RoleR\x04Role\x12E\n" +
	"\fTradeProfile\x18\x10 \x01(\v2!.tradeprofile.TradeProfileDetailsR\fTradeProfile\x12\"\n" +
	"\fKYCInquiries\x18\x11 \x03(\tR\fKYCInquiries\x124\n" +
	"\n" +
	"KYCDetails\x18\x12 \x01(\v2\x14.user.UserKYCDetailsR\n" +
	"KYCDetails\x12X\n" +
	"\x16UserDocumentCompliance\x18\x13 \x01(\v2 .document.UserDocumentComplianceR\x16UserDocumentCompliance\x12-\n" +
	"\tKYCStatus\x18\x14 \x01(\x0e2\x0f.user.KYCStatusR\tKYCStatus\x12J\n" +
	"\x10UserTradeProfile\x18\x15 \x01(\v2\x1e.tradeprofile.UserTradeProfileR\x10UserTradeProfile\x12K\n" +
	"\x13ComplianceQuestions\x18\x16 \x03(\v2\x19.user.ComplianceQuestionsR\x13ComplianceQuestions\x12;\n" +
	"\x0eBrokerAccounts\x18\x17 \x03(\v2\x13.user.BrokerAccountR\x0eBrokerAccountsB\r\n" +
	"\v_Employment\"\xab\x03\n" +
	"\n" +
	"Employment\x12\"\n" +
	"\fEmployerName\x18\x01 \x01(\tR\fEmployerName\x12\x1a\n" +
	"\bJobTitle\x18\x02 \x01(\tR\bJobTitle\x128\n" +
	"\tStartDate\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tStartDate\x124\n" +
	"\aEndDate\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aEndDate\x12(\n" +
	"\x04Type\x18\x05 \x01(\x0e2\x14.user.EmploymentTypeR\x04Type\x12\x1f\n" +
	"\bIndustry\x18\x06 \x01(\tH\x00R\bIndustry\x88\x01\x01\x12$\n" +
	"\x06Income\x18\a \x01(\v2\f.user.IncomeR\x06Income\x12/\n" +
	"\aContact\x18\b \x01(\v2\x15.user.EmployerContactR\aContact\x12\x1e\n" +
	"\n" +
	"IsVerified\x18\t \x01(\bR\n" +
	"IsVerified\x12\x1e\n" +
	"\n" +
	"VerifiedAt\x18\n" +
	" \x01(\tR\n" +
	"VerifiedAtB\v\n" +
	"\t_Industry\"q\n" +
	"\x06Income\x12\x16\n" +
	"\x06Amount\x18\x01 \x01(\x02R\x06Amount\x12\x1a\n" +
	"\bCurrency\x18\x02 \x01(\tR\bCurrency\x123\n" +
	"\tFrequency\x18\x03 \x01(\x0e2\x15.user.IncomeFrequencyR\tFrequency\"k\n" +
	"\x0fEmployerContact\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x14\n" +
	"\x05Email\x18\x02 \x01(\tR\x05Email\x12\x14\n" +
	"\x05Phone\x18\x03 \x01(\tR\x05Phone\x12\x18\n" +
	"\aAddress\x18\x04 \x01(\tR\aAddress\"\x81\x01\n" +
	"\x04User\x12%\n" +
	"\x04User\x18\x01 \x01(\v2\x11.user.UserDetailsR\x04User\x12.\n" +
	"\bMetaData\x18\x02 \x01(\v2\x12.metadata.MetaDataR\bMetaData\x12\"\n" +
	"\x05Audit\x18\x03 \x01(\v2\f.audit.AuditR\x05Audit\"\x86\x01\n" +
	"\x06UserID\x12\x16\n" +
	"\x06UserID\x18\x01 \x01(\tR\x06UserID\x12&\n" +
	"\x0eOrganizationID\x18\x02 \x01(\tR\x0eOrganizationID\x120\n" +
	"\aNetwork\x18\x03 \x01(\x0e2\x11.metadata.NetworkH\x00R\aNetwork\x88\x01\x01B\n" +
	"\n" +
	"\b_Network\"@\n" +
	"\x06Social\x12\x10\n" +
	"\x03URL\x18\x01 \x01(\tR\x03URL\x12$\n" +
	"\x04Type\x18\x02 \x01(\x0e2\x10.user.SocialTypeR\x04Type\"\x90\x01\n" +
	"\x06Wallet\x12\x18\n" +
	"\aAddress\x18\x01 \x01(\tR\aAddress\x12\x14\n" +
	"\x05Alias\x18\x02 \x01(\tR\x05Alias\x12$\n" +
	"\x04Type\x18\x03 \x01(\x0e2\x10.user.WalletTypeR\x04Type\x120\n" +
	"\n" +
	"SignerType\x18\x04 \x01(\x0e2\x10.user.SignerTypeR\n" +
	"SignerType\"T\n" +
	"\bUserList\x12 \n" +
	"\x05Users\x18\x01 \x03(\v2\n" +
	".user.UserR\x05Users\x12\x1b\n" +
	"\x06Offset\x18\x02 \x01(\x05H\x00R\x06Offset\x88\x01\x01B\t\n" +
	"\a_Offset\"\xdb\x01\n" +
	"\rStatusMessage\x12\x16\n" +
	"\x06UserID\x18\x01 \x01(\tR\x06UserID\x12&\n" +
	"\x0eOrganizationID\x18\x02 \x01(\tR\x0eOrganizationID\x12(\n" +
	"\x06Status\x18\x03 \x01(\x0e2\x10.user.UserStatusR\x06Status\x120\n" +
	"\aNetwork\x18\x04 \x01(\x0e2\x11.metadata.NetworkH\x00R\aNetwork\x88\x01\x01\x12\"\n" +
	"\x05Audit\x18\x05 \x01(\v2\f.audit.AuditR\x05AuditB\n" +
	"\n" +
	"\b_Network\"\xa7\x03\n" +
	"\x06Filter\x12\x18\n" +
	"\aUserIDs\x18\x01 \x03(\tR\aUserIDs\x120\n" +
	"\aNetwork\x18\x02 \x01(\x0e2\x11.metadata.NetworkH\x00R\aNetwork\x88\x01\x01\x12&\n" +
	"\x0eOrganizationID\x18\x03 \x01(\tR\x0eOrganizationID\x12\x1b\n" +
	"\x06Offset\x18\x04 \x01(\x05H\x01R\x06Offset\x88\x01\x01\x12\x19\n" +
	"\x05Limit\x18\x05 \x01(\x05H\x02R\x05Limit\x88\x01\x01\x12!\n" +
	"\tInquiryID\x18\x06 \x01(\tH\x03R\tInquiryID\x88\x01\x01\x12-\n" +
	"\x06Status\x18\a \x01(\x0e2\x10.user.UserStatusH\x04R\x06Status\x88\x01\x01\x12(\n" +
	"\x0fExternalUserIDs\x18\b \x03(\tR\x0fExternalUserIDs\x12)\n" +
	"\rWalletAddress\x18\t \x01(\tH\x05R\rWalletAddress\x88\x01\x01B\n" +
	"\n" +
	"\b_NetworkB\t\n" +
	"\a_OffsetB\b\n" +
	"\x06_LimitB\f\n" +
	"\n" +
	"_InquiryIDB\t\n" +
	"\a_StatusB\x10\n" +
	"\x0e_WalletAddress\"?\n" +
	"\x13ComplianceQuestions\x12 \n" +
	"\x03USA\x18\x01 \x01(\v2\t.user.USAH\x00R\x03USA\x88\x01\x01B\x06\n" +
	"\x04_USA\"\xe8\x02\n" +
	"\x03USA\x12:\n" +
	"\n" +
	"RecordedAt\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"RecordedAt\x12(\n" +
	"\x0fYearsExperience\x18\x02 \x01(\x03R\x0fYearsExperience\x12\"\n" +
	"\fAnnualIncome\x18\x03 \x01(\x03R\fAnnualIncome\x12\x1a\n" +
	"\bNetWorth\x18\x04 \x01(\x03R\bNetWorth\x12O\n" +
	"\x14ConversionImportance\x18\x05 \x01(\x0e2\x1b.user.LiquidationImportanceR\x14ConversionImportance\x121\n" +
	"\tTolerance\x18\x06 \x01(\x0e2\x13.user.RiskToleranceR\tTolerance\x127\n" +
	"\tObjective\x18\a \x01(\x0e2\x19.user.InvestmentObjectiveR\tObjective\"\xa0\x01\n" +
	"\rBrokerAccount\x12\x1c\n" +
	"\tAccountID\x18\x01 \x01(\tR\tAccountID\x12-\n" +
	"\x06Broker\x18\x02 \x01(\x0e2\x15.order.ClearingBrokerR\x06Broker\x12&\n" +
	"\x0eOrganizationID\x18\x03 \x01(\tR\x0eOrganizationID\x12\x1a\n" +
	"\bProfiles\x18\x04 \x03(\tR\bProfiles*\xba\x01\n" +
	"\tKYCStatus\x12\x1a\n" +
	"\x16KYC_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12KYC_STATUS_PENDING\x10\x01\x12\x18\n" +
	"\x14KYC_STATUS_IN_REVIEW\x10\x02\x12\x17\n" +
	"\x13KYC_STATUS_APPROVED\x10\x03\x12\x17\n" +
	"\x13KYC_STATUS_REJECTED\x10\x04\x12\x15\n" +
	"\x11KYC_STATUS_FAILED\x10\x05\x12\x16\n" +
	"\x12KYC_STATUS_EXPIRED\x10\x06*\x8b\x01\n" +
	"\x0eEmploymentType\x12\x1b\n" +
	"\x17NOT_USED_EMPLOYMENTTYPE\x10\x00\x12\r\n" +
	"\tFULL_TIME\x10\x01\x12\r\n" +
	"\tPART_TIME\x10\x02\x12\f\n" +
	"\bCONTRACT\x10\x03\x12\r\n" +
	"\tFREELANCE\x10\x04\x12\x11\n" +
	"\rSELF_EMPLOYED\x10\x05\x12\x0e\n" +
	"\n" +
	"INTERNSHIP\x10\x06*q\n" +
	"\x0fIncomeFrequency\x12\x1c\n" +
	"\x18NOT_USED_INCOMEFREQUENCY\x10\x00\x12\n" +
	"\n" +
	"\x06HOURLY\x10\x01\x12\n" +
	"\n" +
	"\x06WEEKLY\x10\x02\x12\r\n" +
	"\tBI_WEEKLY\x10\x03\x12\v\n" +
	"\aMONTHLY\x10\x04\x12\f\n" +
	"\bANNUALLY\x10\x05*t\n" +
	"\n" +
	"SignerType\x12\x17\n" +
	"\x13NOT_USER_SIGNETTYPE\x10\x00\x12\x0e\n" +
	"\n" +
	"MOBILE_APP\x10\x01\x12\x10\n" +
	"\fBROWSER_LEAP\x10\x02\x12\x18\n" +
	"\x14BROWSER_COSMOSTATION\x10\x03\x12\x11\n" +
	"\rBROWSER_KEPLR\x10\x04*H\n" +
	"\n" +
	"UserStatus\x12\x17\n" +
	"\x13NOT_USED_USERSTATUS\x10\x00\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x01\x12\x15\n" +
	"\x11ADMIN_DEACTIVATED\x10\x02*G\n" +
	"\n" +
	"WalletType\x12\x17\n" +
	"\x13NOT_USED_WALLETTYPE\x10\x00\x12\b\n" +
	"\x04TFSA\x10\x01\x12\b\n" +
	"\x04RRSP\x10\x02\x12\f\n" +
	"\bSTANDARD\x10\x03*\x9d\x01\n" +
	"\n" +
	"SocialType\x12\x17\n" +
	"\x13NOT_USED_SOCIALTYPE\x10\x00\x12\v\n" +
	"\aWEBSITE\x10\x01\x12\n" +
	"\n" +
	"\x06GITHUB\x10\x02\x12\n" +
	"\n" +
	"\x06REDDIT\x10\x03\x12\v\n" +
	"\aDISCORD\x10\x04\x12\v\n" +
	"\aTWITTER\x10\x05\x12\f\n" +
	"\bFACEBOOK\x10\x06\x12\f\n" +
	"\bTELEGRAM\x10\a\x12\r\n" +
	"\tINSTAGRAM\x10\b\x12\f\n" +
	"\bLINKEDIN\x10\t*i\n" +
	"\x15LiquidationImportance\x12\x12\n" +
	"\x0eVERY_IMPORTANT\x10\x00\x12\x16\n" +
	"\x12SOMEWHAT_IMPORTANT\x10\x01\x12\x11\n" +
	"\rNOT_IMPORTANT\x10\x02\x12\x11\n" +
	"\rNO_PREFERENCE\x10\x03*}\n" +
	"\rRiskTolerance\x12\x10\n" +
	"\fCONSERVATIVE\x10\x00\x12\x1b\n" +
	"\x17MODERATELY_CONSERVATIVE\x10\x01\x12\f\n" +
	"\bMODERATE\x10\x02\x12\x19\n" +
	"\x15MODERATELY_AGGRESSIVE\x10\x03\x12\x14\n" +
	"\x10SIGNIFICANT_RISK\x10\x04*\x95\x01\n" +
	"\x13InvestmentObjective\x12\n" +
	"\n" +
	"\x06INCOME\x10\x00\x12\f\n" +
	"\bBALANCED\x10\x01\x12\x15\n" +
	"\x11GROWTH_AND_INCOME\x10\x02\x12\x19\n" +
	"\x15SAFE_LONG_TERM_GROWTH\x10\x03\x12!\n" +
	"\x1dGREATER_RISK_LONG_TERM_GROWTH\x10\x04\x12\x0f\n" +
	"\vSPECULATION\x10\x05B-Z+github.com/sologenic/com-fs-user-model;userb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_enumTypes = make([]protoimpl.EnumInfo, 10)
var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_user_proto_goTypes = []any{
	(KYCStatus)(0),              // 0: user.KYCStatus
	(EmploymentType)(0),         // 1: user.EmploymentType
	(IncomeFrequency)(0),        // 2: user.IncomeFrequency
	(SignerType)(0),             // 3: user.SignerType
	(UserStatus)(0),             // 4: user.UserStatus
	(WalletType)(0),             // 5: user.WalletType
	(SocialType)(0),             // 6: user.SocialType
	(LiquidationImportance)(0),  // 7: user.LiquidationImportance
	(RiskTolerance)(0),          // 8: user.RiskTolerance
	(InvestmentObjective)(0),    // 9: user.InvestmentObjective
	(*IDNumber)(nil),            // 10: user.IDNumber
	(*UserKYCDetails)(nil),      // 11: user.UserKYCDetails
	(*UserDetails)(nil),         // 12: user.UserDetails
	(*Employment)(nil),          // 13: user.Employment
	(*Income)(nil),              // 14: user.Income
	(*EmployerContact)(nil),     // 15: user.EmployerContact
	(*User)(nil),                // 16: user.User
	(*UserID)(nil),              // 17: user.UserID
	(*Social)(nil),              // 18: user.Social
	(*Wallet)(nil),              // 19: user.Wallet
	(*UserList)(nil),            // 20: user.UserList
	(*StatusMessage)(nil),       // 21: user.StatusMessage
	(*Filter)(nil),              // 22: user.Filter
	(*ComplianceQuestions)(nil), // 23: user.ComplianceQuestions
	(*USA)(nil),                 // 24: user.USA
	(*BrokerAccount)(nil),       // 25: user.BrokerAccount
	(language.Lang)(0),          // 26: language.Lang
	(role.Role)(0),              // 27: role.Role
	(*com_fs_trade_profile_model.TradeProfileDetails)(nil), // 28: tradeprofile.TradeProfileDetails
	(*com_fs_document_model.UserDocumentCompliance)(nil),   // 29: document.UserDocumentCompliance
	(*com_fs_trade_profile_model.UserTradeProfile)(nil),    // 30: tradeprofile.UserTradeProfile
	(*timestamppb.Timestamp)(nil),                          // 31: google.protobuf.Timestamp
	(*metadata.MetaData)(nil),                              // 32: metadata.MetaData
	(*audit.Audit)(nil),                                    // 33: audit.Audit
	(metadata.Network)(0),                                  // 34: metadata.Network
	(com_fs_order_model.ClearingBroker)(0),                 // 35: order.ClearingBroker
}
var file_user_proto_depIdxs = []int32{
	4,  // 0: user.UserDetails.Status:type_name -> user.UserStatus
	19, // 1: user.UserDetails.Wallets:type_name -> user.Wallet
	18, // 2: user.UserDetails.Socials:type_name -> user.Social
	26, // 3: user.UserDetails.Language:type_name -> language.Lang
	13, // 4: user.UserDetails.Employment:type_name -> user.Employment
	27, // 5: user.UserDetails.Role:type_name -> role.Role
	28, // 6: user.UserDetails.TradeProfile:type_name -> tradeprofile.TradeProfileDetails
	11, // 7: user.UserDetails.KYCDetails:type_name -> user.UserKYCDetails
	29, // 8: user.UserDetails.UserDocumentCompliance:type_name -> document.UserDocumentCompliance
	0,  // 9: user.UserDetails.KYCStatus:type_name -> user.KYCStatus
	30, // 10: user.UserDetails.UserTradeProfile:type_name -> tradeprofile.UserTradeProfile
	23, // 11: user.UserDetails.ComplianceQuestions:type_name -> user.ComplianceQuestions
	25, // 12: user.UserDetails.BrokerAccounts:type_name -> user.BrokerAccount
	31, // 13: user.Employment.StartDate:type_name -> google.protobuf.Timestamp
	31, // 14: user.Employment.EndDate:type_name -> google.protobuf.Timestamp
	1,  // 15: user.Employment.Type:type_name -> user.EmploymentType
	14, // 16: user.Employment.Income:type_name -> user.Income
	15, // 17: user.Employment.Contact:type_name -> user.EmployerContact
	2,  // 18: user.Income.Frequency:type_name -> user.IncomeFrequency
	12, // 19: user.User.User:type_name -> user.UserDetails
	32, // 20: user.User.MetaData:type_name -> metadata.MetaData
	33, // 21: user.User.Audit:type_name -> audit.Audit
	34, // 22: user.UserID.Network:type_name -> metadata.Network
	6,  // 23: user.Social.Type:type_name -> user.SocialType
	5,  // 24: user.Wallet.Type:type_name -> user.WalletType
	3,  // 25: user.Wallet.SignerType:type_name -> user.SignerType
	16, // 26: user.UserList.Users:type_name -> user.User
	4,  // 27: user.StatusMessage.Status:type_name -> user.UserStatus
	34, // 28: user.StatusMessage.Network:type_name -> metadata.Network
	33, // 29: user.StatusMessage.Audit:type_name -> audit.Audit
	34, // 30: user.Filter.Network:type_name -> metadata.Network
	4,  // 31: user.Filter.Status:type_name -> user.UserStatus
	24, // 32: user.ComplianceQuestions.USA:type_name -> user.USA
	31, // 33: user.USA.RecordedAt:type_name -> google.protobuf.Timestamp
	7,  // 34: user.USA.ConversionImportance:type_name -> user.LiquidationImportance
	8,  // 35: user.USA.Tolerance:type_name -> user.RiskTolerance
	9,  // 36: user.USA.Objective:type_name -> user.InvestmentObjective
	35, // 37: user.BrokerAccount.Broker:type_name -> order.ClearingBroker
	38, // [38:38] is the sub-list for method output_type
	38, // [38:38] is the sub-list for method input_type
	38, // [38:38] is the sub-list for extension type_name
	38, // [38:38] is the sub-list for extension extendee
	0,  // [0:38] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	file_user_proto_msgTypes[2].OneofWrappers = []any{}
	file_user_proto_msgTypes[3].OneofWrappers = []any{}
	file_user_proto_msgTypes[7].OneofWrappers = []any{}
	file_user_proto_msgTypes[10].OneofWrappers = []any{}
	file_user_proto_msgTypes[11].OneofWrappers = []any{}
	file_user_proto_msgTypes[12].OneofWrappers = []any{}
	file_user_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      10,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		EnumInfos:         file_user_proto_enumTypes,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
