// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: user-grpc.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_user_grpc_proto protoreflect.FileDescriptor

const file_user_grpc_proto_rawDesc = "" +
	"\n" +
	"\x0fuser-grpc.proto\x12\x04user\x1a\x1bgoogle/protobuf/empty.proto\x1a\n" +
	"user.proto2\x92\x01\n" +
	"\vUserService\x12!\n" +
	"\x03Get\x12\f.user.UserID\x1a\n" +
	".user.User\"\x00\x12$\n" +
	"\x06Upsert\x12\n" +
	".user.User\x1a\f.user.UserID\"\x00\x12:\n" +
	"\tSetStatus\x12\x13.user.StatusMessage\x1a\x16.google.protobuf.Empty\"\x00B-Z+github.com/sologenic/com-fs-user-model;userb\x06proto3"

var file_user_grpc_proto_goTypes = []any{
	(*UserID)(nil),        // 0: user.UserID
	(*User)(nil),          // 1: user.User
	(*StatusMessage)(nil), // 2: user.StatusMessage
	(*emptypb.Empty)(nil), // 3: google.protobuf.Empty
}
var file_user_grpc_proto_depIdxs = []int32{
	0, // 0: user.UserService.Get:input_type -> user.UserID
	1, // 1: user.UserService.Upsert:input_type -> user.User
	2, // 2: user.UserService.SetStatus:input_type -> user.StatusMessage
	1, // 3: user.UserService.Get:output_type -> user.User
	0, // 4: user.UserService.Upsert:output_type -> user.UserID
	3, // 5: user.UserService.SetStatus:output_type -> google.protobuf.Empty
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_grpc_proto_init() }
func file_user_grpc_proto_init() {
	if File_user_grpc_proto != nil {
		return
	}
	file_user_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_grpc_proto_rawDesc), len(file_user_grpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_grpc_proto_goTypes,
		DependencyIndexes: file_user_grpc_proto_depIdxs,
	}.Build()
	File_user_grpc_proto = out.File
	file_user_grpc_proto_goTypes = nil
	file_user_grpc_proto_depIdxs = nil
}
