// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v6.30.2
// source: user-fundings.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";
import {
  ClearingBroker,
  clearingBrokerFromJSON,
  clearingBrokerToJSON,
} from "./sologenic/com-fs-utils-lib/models/order-properties/order-properties";

export const protobufPackage = "user";

export enum SignerType {
  NOT_USER_SIGNETTYPE = 0,
  MOBILE_APP = 1,
  BROWSER_LEAP = 2,
  BROWSER_COSMOSTATION = 3,
  BROWSER_KEPLR = 4,
  UNRECOGNIZED = -1,
}

export function signerTypeFromJSON(object: any): SignerType {
  switch (object) {
    case 0:
    case "NOT_USER_SIGNETTYPE":
      return SignerType.NOT_USER_SIGNETTYPE;
    case 1:
    case "MOBILE_APP":
      return SignerType.MOBILE_APP;
    case 2:
    case "BROWSER_LEAP":
      return SignerType.BROWSER_LEAP;
    case 3:
    case "BROWSER_COSMOSTATION":
      return SignerType.BROWSER_COSMOSTATION;
    case 4:
    case "BROWSER_KEPLR":
      return SignerType.BROWSER_KEPLR;
    case -1:
    case "UNRECOGNIZED":
    default:
      return SignerType.UNRECOGNIZED;
  }
}

export function signerTypeToJSON(object: SignerType): string {
  switch (object) {
    case SignerType.NOT_USER_SIGNETTYPE:
      return "NOT_USER_SIGNETTYPE";
    case SignerType.MOBILE_APP:
      return "MOBILE_APP";
    case SignerType.BROWSER_LEAP:
      return "BROWSER_LEAP";
    case SignerType.BROWSER_COSMOSTATION:
      return "BROWSER_COSMOSTATION";
    case SignerType.BROWSER_KEPLR:
      return "BROWSER_KEPLR";
    case SignerType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum WalletType {
  NOT_USED_WALLETTYPE = 0,
  TFSA = 1,
  RRSP = 2,
  STANDARD = 3,
  UNRECOGNIZED = -1,
}

export function walletTypeFromJSON(object: any): WalletType {
  switch (object) {
    case 0:
    case "NOT_USED_WALLETTYPE":
      return WalletType.NOT_USED_WALLETTYPE;
    case 1:
    case "TFSA":
      return WalletType.TFSA;
    case 2:
    case "RRSP":
      return WalletType.RRSP;
    case 3:
    case "STANDARD":
      return WalletType.STANDARD;
    case -1:
    case "UNRECOGNIZED":
    default:
      return WalletType.UNRECOGNIZED;
  }
}

export function walletTypeToJSON(object: WalletType): string {
  switch (object) {
    case WalletType.NOT_USED_WALLETTYPE:
      return "NOT_USED_WALLETTYPE";
    case WalletType.TFSA:
      return "TFSA";
    case WalletType.RRSP:
      return "RRSP";
    case WalletType.STANDARD:
      return "STANDARD";
    case WalletType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface Wallet {
  Address: string;
  Alias: string;
  Type: WalletType;
  SignerType: SignerType;
  /** List of organizations linked to this wallet address */
  Organizations: string[];
}

export interface BankAccount {
  AccountName: string;
  /** user's identifier in the bank account */
  BankName: string;
  /** bank address */
  BankAddress: string;
  /** bank account number */
  AccountNumber: string;
  /** bank routing number */
  ABA: string;
  SWIFT: string;
  IBAN: string;
}

export interface BrokerAccount {
  /** user's identifier in the broker account */
  AccountID: string;
  /** "RQD", etc. */
  Broker: ClearingBroker;
  /** broker identifier */
  OrganizationID: string;
  /** bank account profiles for the broker account */
  Profiles: string[];
}

function createBaseWallet(): Wallet {
  return { Address: "", Alias: "", Type: 0, SignerType: 0, Organizations: [] };
}

export const Wallet = {
  encode(message: Wallet, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.Address !== "") {
      writer.uint32(10).string(message.Address);
    }
    if (message.Alias !== "") {
      writer.uint32(18).string(message.Alias);
    }
    if (message.Type !== 0) {
      writer.uint32(24).int32(message.Type);
    }
    if (message.SignerType !== 0) {
      writer.uint32(32).int32(message.SignerType);
    }
    for (const v of message.Organizations) {
      writer.uint32(42).string(v!);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Wallet {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWallet();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.Address = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.Alias = reader.string();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.Type = reader.int32() as any;
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.SignerType = reader.int32() as any;
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.Organizations.push(reader.string());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Wallet {
    return {
      Address: isSet(object.Address) ? globalThis.String(object.Address) : "",
      Alias: isSet(object.Alias) ? globalThis.String(object.Alias) : "",
      Type: isSet(object.Type) ? walletTypeFromJSON(object.Type) : 0,
      SignerType: isSet(object.SignerType) ? signerTypeFromJSON(object.SignerType) : 0,
      Organizations: globalThis.Array.isArray(object?.Organizations)
        ? object.Organizations.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: Wallet): unknown {
    const obj: any = {};
    if (message.Address !== "") {
      obj.Address = message.Address;
    }
    if (message.Alias !== "") {
      obj.Alias = message.Alias;
    }
    if (message.Type !== 0) {
      obj.Type = walletTypeToJSON(message.Type);
    }
    if (message.SignerType !== 0) {
      obj.SignerType = signerTypeToJSON(message.SignerType);
    }
    if (message.Organizations?.length) {
      obj.Organizations = message.Organizations;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Wallet>, I>>(base?: I): Wallet {
    return Wallet.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Wallet>, I>>(object: I): Wallet {
    const message = createBaseWallet();
    message.Address = object.Address ?? "";
    message.Alias = object.Alias ?? "";
    message.Type = object.Type ?? 0;
    message.SignerType = object.SignerType ?? 0;
    message.Organizations = object.Organizations?.map((e) => e) || [];
    return message;
  },
};

function createBaseBankAccount(): BankAccount {
  return { AccountName: "", BankName: "", BankAddress: "", AccountNumber: "", ABA: "", SWIFT: "", IBAN: "" };
}

export const BankAccount = {
  encode(message: BankAccount, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.AccountName !== "") {
      writer.uint32(10).string(message.AccountName);
    }
    if (message.BankName !== "") {
      writer.uint32(18).string(message.BankName);
    }
    if (message.BankAddress !== "") {
      writer.uint32(26).string(message.BankAddress);
    }
    if (message.AccountNumber !== "") {
      writer.uint32(34).string(message.AccountNumber);
    }
    if (message.ABA !== "") {
      writer.uint32(42).string(message.ABA);
    }
    if (message.SWIFT !== "") {
      writer.uint32(50).string(message.SWIFT);
    }
    if (message.IBAN !== "") {
      writer.uint32(58).string(message.IBAN);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): BankAccount {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBankAccount();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.AccountName = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.BankName = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.BankAddress = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.AccountNumber = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.ABA = reader.string();
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.SWIFT = reader.string();
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.IBAN = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BankAccount {
    return {
      AccountName: isSet(object.AccountName) ? globalThis.String(object.AccountName) : "",
      BankName: isSet(object.BankName) ? globalThis.String(object.BankName) : "",
      BankAddress: isSet(object.BankAddress) ? globalThis.String(object.BankAddress) : "",
      AccountNumber: isSet(object.AccountNumber) ? globalThis.String(object.AccountNumber) : "",
      ABA: isSet(object.ABA) ? globalThis.String(object.ABA) : "",
      SWIFT: isSet(object.SWIFT) ? globalThis.String(object.SWIFT) : "",
      IBAN: isSet(object.IBAN) ? globalThis.String(object.IBAN) : "",
    };
  },

  toJSON(message: BankAccount): unknown {
    const obj: any = {};
    if (message.AccountName !== "") {
      obj.AccountName = message.AccountName;
    }
    if (message.BankName !== "") {
      obj.BankName = message.BankName;
    }
    if (message.BankAddress !== "") {
      obj.BankAddress = message.BankAddress;
    }
    if (message.AccountNumber !== "") {
      obj.AccountNumber = message.AccountNumber;
    }
    if (message.ABA !== "") {
      obj.ABA = message.ABA;
    }
    if (message.SWIFT !== "") {
      obj.SWIFT = message.SWIFT;
    }
    if (message.IBAN !== "") {
      obj.IBAN = message.IBAN;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BankAccount>, I>>(base?: I): BankAccount {
    return BankAccount.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BankAccount>, I>>(object: I): BankAccount {
    const message = createBaseBankAccount();
    message.AccountName = object.AccountName ?? "";
    message.BankName = object.BankName ?? "";
    message.BankAddress = object.BankAddress ?? "";
    message.AccountNumber = object.AccountNumber ?? "";
    message.ABA = object.ABA ?? "";
    message.SWIFT = object.SWIFT ?? "";
    message.IBAN = object.IBAN ?? "";
    return message;
  },
};

function createBaseBrokerAccount(): BrokerAccount {
  return { AccountID: "", Broker: 0, OrganizationID: "", Profiles: [] };
}

export const BrokerAccount = {
  encode(message: BrokerAccount, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.AccountID !== "") {
      writer.uint32(10).string(message.AccountID);
    }
    if (message.Broker !== 0) {
      writer.uint32(16).int32(message.Broker);
    }
    if (message.OrganizationID !== "") {
      writer.uint32(26).string(message.OrganizationID);
    }
    for (const v of message.Profiles) {
      writer.uint32(34).string(v!);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): BrokerAccount {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBrokerAccount();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.AccountID = reader.string();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.Broker = reader.int32() as any;
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.OrganizationID = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.Profiles.push(reader.string());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BrokerAccount {
    return {
      AccountID: isSet(object.AccountID) ? globalThis.String(object.AccountID) : "",
      Broker: isSet(object.Broker) ? clearingBrokerFromJSON(object.Broker) : 0,
      OrganizationID: isSet(object.OrganizationID) ? globalThis.String(object.OrganizationID) : "",
      Profiles: globalThis.Array.isArray(object?.Profiles) ? object.Profiles.map((e: any) => globalThis.String(e)) : [],
    };
  },

  toJSON(message: BrokerAccount): unknown {
    const obj: any = {};
    if (message.AccountID !== "") {
      obj.AccountID = message.AccountID;
    }
    if (message.Broker !== 0) {
      obj.Broker = clearingBrokerToJSON(message.Broker);
    }
    if (message.OrganizationID !== "") {
      obj.OrganizationID = message.OrganizationID;
    }
    if (message.Profiles?.length) {
      obj.Profiles = message.Profiles;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BrokerAccount>, I>>(base?: I): BrokerAccount {
    return BrokerAccount.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BrokerAccount>, I>>(object: I): BrokerAccount {
    const message = createBaseBrokerAccount();
    message.AccountID = object.AccountID ?? "";
    message.Broker = object.Broker ?? 0;
    message.OrganizationID = object.OrganizationID ?? "";
    message.Profiles = object.Profiles?.map((e) => e) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
