// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.29.3
// source: sologenic/com-fs-asset-model/domain/currency/currency.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";

export const protobufPackage = "currency";

export interface Currency {
  /** User-entered ticker with format:[a-zA-Z0-9]{1,45}. e.g., APPL, PLTR, MSFT */
  Symbol: string;
  /** Auto-incremented version (no leading zeros) with max length 3 characters (values 1 to 999) */
  Version: string;
}

function createBaseCurrency(): Currency {
  return { Symbol: "", Version: "" };
}

export const Currency = {
  encode(message: Currency, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.Symbol !== "") {
      writer.uint32(10).string(message.Symbol);
    }
    if (message.Version !== "") {
      writer.uint32(18).string(message.Version);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Currency {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCurrency();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.Symbol = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.Version = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Currency {
    return {
      Symbol: isSet(object.Symbol) ? globalThis.String(object.Symbol) : "",
      Version: isSet(object.Version) ? globalThis.String(object.Version) : "",
    };
  },

  toJSON(message: Currency): unknown {
    const obj: any = {};
    if (message.Symbol !== "") {
      obj.Symbol = message.Symbol;
    }
    if (message.Version !== "") {
      obj.Version = message.Version;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Currency>, I>>(base?: I): Currency {
    return Currency.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Currency>, I>>(object: I): Currency {
    const message = createBaseCurrency();
    message.Symbol = object.Symbol ?? "";
    message.Version = object.Version ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
